# Generated by Django 4.1.7 on 2026-07-01 11:35

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BolsaPuntos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente_id', models.IntegerField()),
                ('fecha_asignacion', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('puntaje_asignado', models.IntegerField(default=0)),
                ('puntaje_utilizado', models.IntegerField(default=0)),
                ('saldo_puntos', models.IntegerField(default=0)),
                ('monto_operacion', models.IntegerField(default=0)),
                ('vencido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['fecha_asignacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteFidelizacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=30)),
                ('tipo_documento', models.CharField(default='CI', max_length=30)),
                ('nacionalidad', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.CharField(blank=True, default='', max_length=120)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoUsoPuntos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=120)),
                ('puntos_requeridos', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoFidelizacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('proxima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('bolsas_vencidas', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReglaAsignacionPuntos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('limite_inferior', models.IntegerField(default=0)),
                ('limite_superior', models.IntegerField(blank=True, null=True)),
                ('monto_equivalencia', models.IntegerField()),
            ],
            options={
                'ordering': ['limite_inferior', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UsoPuntos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente_id', models.IntegerField()),
                ('concepto_id', models.IntegerField()),
                ('puntaje_utilizado', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('detalle', djongo.models.fields.JSONField(default=list)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VencimientoPuntos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_duracion', models.IntegerField()),
            ],
            options={
                'ordering': ['fecha_inicio', 'id'],
            },
        ),
    ]
